#!/bin/bash
set -euo pipefail
echo "postBuild started successfully"

# Install additional R packages
# if not available as conda package
# R -e "install.packages('diagram', repos='http://cran.rstudio.com/')" 
# the cran.rstudio is not optimised for Ubuntu 24.04, use P3M miror below instead
# Using faster P3M mirror pour Ubuntu 24.04
R -e "install.packages('diagram', repos='https://packagemanager.posit.co/cran/__linux__/jammy/latest')"
R -e "install.packages('fastmap', repos='https://packagemanager.posit.co/cran/__linux__/jammy/latest')"
R -e "install.packages('swirl', repos='https://packagemanager.posit.co/cran/__linux__/jammy/latest', dependencies = TRUE)"

# Install R/Bioconductor package
# https://bioconductor.org/install/
R -e "install.packages('BiocManager', repos='https://packagemanager.posit.co/cran/__linux__/jammy/latest')"
R -e "BiocManager::install()"

# Then install required packages
# Biostrings: Efficient manipulation of biological strings
# https://bioconductor.org/packages/release/bioc/html/Biostrings.html
R -e "BiocManager::install('Biostrings', update = FALSE)"
R -e "BiocManager::install('biomaRt', update = FALSE)"
R -e "BiocManager::install('limma', update = FALSE)"
R -e "BiocManager::install('ggtree', update = FALSE)"
R -e "BiocManager::install('edgeR', update = FALSE)"
R -e "BiocManager::install('ComplexHeatmap', update = FALSE)"
R -e "BiocManager::install('enrichplot', update = FALSE)"
R -e "BiocManager::install('clusterProfiler', update = FALSE)"
R -e "BiocManager::install('org.Hs.eg.db', update = FALSE)"
R -e "BiocManager::install('org.Mm.eg.db', update = FALSE)"
R -e "BiocManager::install('ReactomePA', update = FALSE)"
R -e "BiocManager::install('GeneBreak', update = FALSE)"
R -e "BiocManager::install('GenomicRanges', update = FALSE)"
R -e "BiocManager::install('EnhancedVolcano', update = FALSE)"
R -e "BiocManager::install('DESeq2', update = FALSE)"

#R -e "remotes::install_github('YuLab-SMU/ggtree')"

# NOT TESTED : check that the R is correctly installed
#R -e "IRkernel::installspec(user = FALSE)"

echo "postBuild finished successfully"
